apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: CoreProvider
metadata:
  name: cluster-api
  namespace: capi-operator-system
spec:
  version: v1.9.6
  manager:
    featureGates:
      ClusterResourceSet: true
      ClusterTopology: true
      KubeadmBootstrapFormatIgnition: true
      MachinePool: true
      MachineSetPreflightChecks: false
      RuntimeSDK: false
