apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: test
  labels:
    cloud: hetzner
    cni: cilium
    gitops: flux
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
        - 10.200.0.0/16
    services:
      cidrBlocks:
        - 10.96.0.0/12
  topology:
    variables:
      - name: imageName
        value: cluster-api-flatcar-stable-4152.2.2-v1.32.4-1745487823
      - name: instanceType
        value: cax21
    class: hetzner-0.1.0
    version: v1.32.4
    controlPlane:
      replicas: 3
      variables:
        overrides:
          - name: imageName
            value: cluster-api-flatcar-stable-4152.2.2-v1.32.4-1745487823
          - name: instanceType
            value: cax11
    workers:
      machineDeployments:
        - class: worker
          name: worker
          replicas: 2
          # do not set replicas when using cluster-autoscaler:
          # https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/clusterapi/README.md#autoscaling-with-clusterclass-and-managed-topologies
          # metadata:
          #   annotations:
          #     cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "3"
          #     cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "5"
          #     cluster.x-k8s.io/autoscaling-options-scaledownutilizationthreshold: "0.7"
          #     capacity.cluster-autoscaler.kubernetes.io/taints: "cni.istio.io/not-ready"
