apiVersion: cluster.x-k8s.io/v1beta1
kind: ClusterClass
metadata:
  name: hetzner-0.1.0
spec:
  variables:
    - name: imageName
      required: true
      schema:
        openAPIV3Schema:
          type: string
    - name: instanceType
      required: true
      schema:
        openAPIV3Schema:
          type: string
  patches:
    - name: worker
      definitions:
        - jsonPatches:
            - op: replace
              path: /spec/template/spec/imageName
              valueFrom:
                variable: imageName
            - op: replace
              path: /spec/template/spec/type
              valueFrom:
                variable: instanceType
          selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HCloudMachineTemplate
            matchResources:
              machineDeploymentClass:
                names:
                  - worker
    - name: control-plane
      definitions:
        - jsonPatches:
            - op: replace
              path: /spec/template/spec/imageName
              valueFrom:
                variable: imageName
            - op: replace
              path: /spec/template/spec/type
              valueFrom:
                variable: instanceType
          selector:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HCloudMachineTemplate
            matchResources:
              controlPlane: true
  controlPlane:
    ref:
      apiVersion: controlplane.cluster.x-k8s.io/v1beta1
      kind: KubeadmControlPlaneTemplate
      name: kubeadm-control-plane-0.1.0
    machineInfrastructure:
      ref:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: control-plane-0.1.0
    machineHealthCheck:
      maxUnhealthy: 100%
      nodeStartupTimeout: 15m
      remediationTemplate:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudRemediationTemplate
        name: hrt-0.1.0
      unhealthyConditions:
        - status: Unknown
          timeout: 180s
          type: Ready
        - status: "False"
          timeout: 180s
          type: Ready
  infrastructure:
    ref:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: HetznerClusterTemplate
      name: hetzner-0.1.0
  workers:
    machineDeployments:
    - class: worker
      template:
        bootstrap:
          ref:
            apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
            kind: KubeadmConfigTemplate
            name: kubeadm-config-0.1.0
        infrastructure:
          ref:
            apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
            kind: HCloudMachineTemplate
            name: worker-0.1.0
      machineHealthCheck:
        maxUnhealthy: 100%
        nodeStartupTimeout: 15m
        remediationTemplate:
          apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
          kind: HCloudRemediationTemplate
          name: hrt-0.1.0
        unhealthyConditions:
          - status: Unknown
            timeout: 180s
            type: Ready
          - status: "False"
            timeout: 180s
            type: Ready
