apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: HcloudRemediationTemplate
metadata:
  name: hrt-0.1.0
spec:
  template:
    spec:
      strategy:
        retryLimit: 1
        timeout: 180s
        type: Reboot
