apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: cilium-hetzner-0.1.0
spec:
  clusterSelector:
    matchLabels:
      cni: cilium
  repoURL: https://helm.cilium.io/
  chartName: cilium
  version: 1.14.4
  namespace: kube-system
  options:
    waitForJobs: true
    wait: true
    timeout: 5m
  valuesTemplate: |
    cni:
      exclusive: false # required for istio-cni

    rollOutCiliumPods: true
    priorityClassName: "system-node-critical"

    hostFirewall:
      enabled: true

    hubble:
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
      relay:
        enabled: true
        rollOutPods: true
      ui:
        enabled: true
        rollOutPods: true
    ipam:
      mode: "kubernetes"

    kubeProxyReplacement: "partial"

    operator:
      rollOutPods: true
      priorityClassName: "system-node-critical"
