apiVersion: addons.cluster.x-k8s.io/v1alpha1
kind: HelmChartProxy
metadata:
  name: hccm-hetzner-0.1.0
spec:
  clusterSelector:
    matchLabels:
      cloud: hetzner
  repoURL: https://charts.hetzner.cloud
  chartName: hcloud-cloud-controller-manager
  version: 1.23.0
  namespace: kube-system
  valuesTemplate: |
    env:
      HCLOUD_LOAD_BALANCERS_DISABLE_PRIVATE_INGRESS:
        value: "true"
      HCLOUD_LOAD_BALANCERS_USE_PRIVATE_IP:
        value: "true"
      HCLOUD_NETWORK_ROUTES_ENABLED:
        value: "false"
      HCLOUD_TOKEN:
        valueFrom:
          secretKeyRef:
            name: hetzner-test
            key: hcloud
    networking:
      enabled: true
      clusterCIDR: 10.200.0.0/16
      network:
        valueFrom:
          secretKeyRef:
            name: hetzner-test
            key: network
    additionalTolerations:
    - key: "node.cluster.x-k8s.io/uninitialized"
      operator: "Exists"
      effect: "NoSchedule"
