apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kubeadm
spec:
  version: v1.9.6
  manager:
    featureGates:
      MachinePool: true
      ClusterTopology: true
      KubeadmBootstrapFormatIgnition: true
